auto: true # false
# server: true
# server_port: 4000
# destination: ./_site
# source: ./
# markdown: maruku # rdiscount
# pygments: false # github default true
lsi: false # github default false - produces latent semantic (related) index of posts
permalink: /blog/:year/:month/:day/:title # date
# paginate: 10
# maruku:
#   use_tex:    false
#   use_divs:   false
#   png_dir:    images/latex
#   png_url:    /images/latex
exclude:
 - NOTES.txt
 - .git
 - .gitignore
 - Rakefile
 - Capfile
 - config
 - lib

# custom globals
url: http://www.metafeather.net/
# prefix: blog